// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvQlSo-QKYYjclrgnmbmW7llb0eSEllQI',
    appId: '1:1004078834120:web:8fca691ae4a597a6a160fd',
    messagingSenderId: '1004078834120',
    projectId: 'dilicia-suvidha',
    authDomain: 'dilicia-suvidha.firebaseapp.com',
    storageBucket: 'dilicia-suvidha.appspot.com',
    measurementId: 'G-VP6FKM2G8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8j0T2KAJ9lIiOMY1hi_L5vrIPsix7Lr0',
    appId: '1:1004078834120:android:1bd0afaf14633927a160fd',
    messagingSenderId: '1004078834120',
    projectId: 'dilicia-suvidha',
    storageBucket: 'dilicia-suvidha.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq25Aad6SAT0BlcoJvIbvVtHYxzUN_sB4',
    appId: '1:1004078834120:ios:81bd8c47219c507aa160fd',
    messagingSenderId: '1004078834120',
    projectId: 'dilicia-suvidha',
    storageBucket: 'dilicia-suvidha.appspot.com',
    iosBundleId: 'com.dilicia.sutraEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq25Aad6SAT0BlcoJvIbvVtHYxzUN_sB4',
    appId: '1:1004078834120:ios:4791d9dd80c3a347a160fd',
    messagingSenderId: '1004078834120',
    projectId: 'dilicia-suvidha',
    storageBucket: 'dilicia-suvidha.appspot.com',
    iosBundleId: 'com.dilicia.sutraEcommerce.RunnerTests',
  );
}
